version: '3.8'

services:
  backend:
    build: ./Backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app
    environment:
      - NODE_ENV=production

  frontend:
    build: ./Frontend
    ports:
      - "8085:80"  
    volumes:
      - ./Frontend:/app
    environment:
      - NODE_ENV=production
